version: '3'
services:
  dbService:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
